name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Test
        run: |
          ls -l
          R=$(curl -k -s https://api.mxooo.cn/yiyan/?type=json)
          echo $R

      - name: Auto green
        run: |
          git config --local user.email "2438211370@qq.com"
          git config --local user.name "lhlyu"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "must be ragged but I stay by your side"
          git push
