name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          R=$(shuf -n1 ./text.txt)
          S=$(curl --compressed https://v1.hitokoto.cn/?c=a&encode=text)
          echo '------------>'
          echo $S
          echo '------------>'
          git config --local user.email "2438211370@qq.com"
          git config --local user.name "lhlyu"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "${R}"
          git push
